const CREAR_TAREA = 'CREAR_TAREA';
const BORRAR_TAREA = 'BORRAR_TAREA';
const EDITAR_TAREA = 'EDITAR_TAREA';
const FILTRAR_TAREA = 'FILTRAR_TAREA';

export { CREAR_TAREA, BORRAR_TAREA, EDITAR_TAREA, FILTRAR_TAREA };