const CREAR_TAREA = 'CREAR_TAREA';
const BORRAR_TAREA = 'BORRAR_TAREA';
const EDITAR_TAREA = 'EDITAR_TAREA';
const FILTRAR_TAREA = 'FILTRAR_TAREA';
const INICIALIZAR_TAREAS = 'INICIALIZAR_TAREAS';

export { CREAR_TAREA, BORRAR_TAREA, EDITAR_TAREA, FILTRAR_TAREA, INICIALIZAR_TAREAS };